# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dynamo_pb2 as dynamo__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dynamo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DynamoServiceStub(object):
    """--- Main service: client → coordinator and coordinator → replica RPCs ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/dynamo.DynamoService/Put',
                request_serializer=dynamo__pb2.PutRequest.SerializeToString,
                response_deserializer=dynamo__pb2.PutReply.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/dynamo.DynamoService/Get',
                request_serializer=dynamo__pb2.GetRequest.SerializeToString,
                response_deserializer=dynamo__pb2.GetReply.FromString,
                _registered_method=True)
        self.ForwardPut = channel.unary_unary(
                '/dynamo.DynamoService/ForwardPut',
                request_serializer=dynamo__pb2.PutRequest.SerializeToString,
                response_deserializer=dynamo__pb2.PutReply.FromString,
                _registered_method=True)
        self.ForwardGet = channel.unary_unary(
                '/dynamo.DynamoService/ForwardGet',
                request_serializer=dynamo__pb2.GetRequest.SerializeToString,
                response_deserializer=dynamo__pb2.GetReply.FromString,
                _registered_method=True)
        self.PutHint = channel.unary_unary(
                '/dynamo.DynamoService/PutHint',
                request_serializer=dynamo__pb2.Hint.SerializeToString,
                response_deserializer=dynamo__pb2.PutReply.FromString,
                _registered_method=True)
        self.DeliverHints = channel.unary_unary(
                '/dynamo.DynamoService/DeliverHints',
                request_serializer=dynamo__pb2.DeliverHintsRequest.SerializeToString,
                response_deserializer=dynamo__pb2.DeliverHintsReply.FromString,
                _registered_method=True)
        self.Gossip = channel.unary_unary(
                '/dynamo.DynamoService/Gossip',
                request_serializer=dynamo__pb2.MembershipList.SerializeToString,
                response_deserializer=dynamo__pb2.MembershipList.FromString,
                _registered_method=True)


class DynamoServiceServicer(object):
    """--- Main service: client → coordinator and coordinator → replica RPCs ---
    """

    def Put(self, request, context):
        """Client -> any node (that node becomes coordinator)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForwardPut(self, request, context):
        """Coordinator -> replica (internal forwarding)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForwardGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutHint(self, request, context):
        """For hinted handoff storage on other nodes and delivery
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeliverHints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Gossip(self, request, context):
        """Gossip membership exchange
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DynamoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=dynamo__pb2.PutRequest.FromString,
                    response_serializer=dynamo__pb2.PutReply.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=dynamo__pb2.GetRequest.FromString,
                    response_serializer=dynamo__pb2.GetReply.SerializeToString,
            ),
            'ForwardPut': grpc.unary_unary_rpc_method_handler(
                    servicer.ForwardPut,
                    request_deserializer=dynamo__pb2.PutRequest.FromString,
                    response_serializer=dynamo__pb2.PutReply.SerializeToString,
            ),
            'ForwardGet': grpc.unary_unary_rpc_method_handler(
                    servicer.ForwardGet,
                    request_deserializer=dynamo__pb2.GetRequest.FromString,
                    response_serializer=dynamo__pb2.GetReply.SerializeToString,
            ),
            'PutHint': grpc.unary_unary_rpc_method_handler(
                    servicer.PutHint,
                    request_deserializer=dynamo__pb2.Hint.FromString,
                    response_serializer=dynamo__pb2.PutReply.SerializeToString,
            ),
            'DeliverHints': grpc.unary_unary_rpc_method_handler(
                    servicer.DeliverHints,
                    request_deserializer=dynamo__pb2.DeliverHintsRequest.FromString,
                    response_serializer=dynamo__pb2.DeliverHintsReply.SerializeToString,
            ),
            'Gossip': grpc.unary_unary_rpc_method_handler(
                    servicer.Gossip,
                    request_deserializer=dynamo__pb2.MembershipList.FromString,
                    response_serializer=dynamo__pb2.MembershipList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dynamo.DynamoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dynamo.DynamoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DynamoService(object):
    """--- Main service: client → coordinator and coordinator → replica RPCs ---
    """

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.DynamoService/Put',
            dynamo__pb2.PutRequest.SerializeToString,
            dynamo__pb2.PutReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.DynamoService/Get',
            dynamo__pb2.GetRequest.SerializeToString,
            dynamo__pb2.GetReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForwardPut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.DynamoService/ForwardPut',
            dynamo__pb2.PutRequest.SerializeToString,
            dynamo__pb2.PutReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForwardGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.DynamoService/ForwardGet',
            dynamo__pb2.GetRequest.SerializeToString,
            dynamo__pb2.GetReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutHint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.DynamoService/PutHint',
            dynamo__pb2.Hint.SerializeToString,
            dynamo__pb2.PutReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeliverHints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.DynamoService/DeliverHints',
            dynamo__pb2.DeliverHintsRequest.SerializeToString,
            dynamo__pb2.DeliverHintsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Gossip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.DynamoService/Gossip',
            dynamo__pb2.MembershipList.SerializeToString,
            dynamo__pb2.MembershipList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
